language: php

php:
  - 5.6

services:
    - docker
  
before_script:
  - echo "extension = fileinfo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = gd.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = phar.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = openssl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  
notifications:
    recipients:
        - hello@cedric.ws
    irc: "chat.freenode.net#kerberos.io"
    email:
        on_success: always
        on_failure: always

after_success:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        cd docker;
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker build -t web .;
            docker tag web kerberos/web:latest;
            docker push kerberos/web:latest;
        else
            docker build --build-arg APP_ENV="$TRAVIS_BRANCH" web .;
            docker tag web kerberos/web:$TRAVIS_BRANCH;
            docker push kerberos/web:$TRAVIS_BRANCH;
        fi
      fi
